# Downloads data files from Princeton
# Any errors will be in log.txt

data_files=(
    'https://algs4.cs.princeton.edu/11model/cards.txt'
    'https://algs4.cs.princeton.edu/11model/cardsUnicode.txt'
    'https://algs4.cs.princeton.edu/11model/tinyAllowlist.txt'
    'https://algs4.cs.princeton.edu/11model/tinyText.txt'
    'https://algs4.cs.princeton.edu/11model/largeAllowlist.txt'
    'https://algs4.cs.princeton.edu/11model/largeText.txt'
    'https://algs4.cs.princeton.edu/11model/in1.txt'
    'https://algs4.cs.princeton.edu/11model/in2.txt'
    'https://algs4.cs.princeton.edu/13stacks/tobe.txt'
    'https://algs4.cs.princeton.edu/14analysis/1Kints.txt'
    'https://algs4.cs.princeton.edu/14analysis/2Kints.txt'
    'https://algs4.cs.princeton.edu/14analysis/4Kints.txt'
    'https://algs4.cs.princeton.edu/14analysis/8Kints.txt'
    'https://algs4.cs.princeton.edu/14analysis/16Kints.txt'
    'https://algs4.cs.princeton.edu/14analysis/32Kints.txt'
    'https://algs4.cs.princeton.edu/15uf/tinyUF.txt'
    'https://algs4.cs.princeton.edu/15uf/mediumUF.txt'
    'https://algs4.cs.princeton.edu/15uf/largeUF.txt'
    'https://algs4.cs.princeton.edu/21elementary/tiny.txt'
    'https://algs4.cs.princeton.edu/21elementary/words3.txt'
    'https://algs4.cs.princeton.edu/24pq/tinyBatch.txt'
    'https://algs4.cs.princeton.edu/24pq/tinyPQ.txt'
    'https://algs4.cs.princeton.edu/24pq/m1.txt'
    'https://algs4.cs.princeton.edu/24pq/m2.txt'
    'https://algs4.cs.princeton.edu/24pq/m3.txt'
    'https://algs4.cs.princeton.edu/31elementary/tinyTale.txt'
    'https://algs4.cs.princeton.edu/31elementary/tale.txt'
    'https://algs4.cs.princeton.edu/31elementary/leipzig100K.txt'
    'https://algs4.cs.princeton.edu/31elementary/leipzig300K.txt'
    'https://algs4.cs.princeton.edu/31elementary/leipzig1M.txt'
    'https://algs4.cs.princeton.edu/31elementary/tinyST.txt'
    'https://algs4.cs.princeton.edu/35applications/blocklist.txt'
    'https://algs4.cs.princeton.edu/35applications/allowlist.txt'
    'https://algs4.cs.princeton.edu/35applications/movies.txt'
    'https://algs4.cs.princeton.edu/35applications/ex1.txt'
    'https://algs4.cs.princeton.edu/35applications/ex2.txt'
    'https://algs4.cs.princeton.edu/35applications/ex3.txt'
    'https://algs4.cs.princeton.edu/35applications/ex4.txt'
    'https://algs4.cs.princeton.edu/41graph/tinyG.txt'
    'https://algs4.cs.princeton.edu/41graph/mediumG.txt'
    'https://algs4.cs.princeton.edu/41graph/largeG.txt'
    'https://algs4.cs.princeton.edu/41graph/tinyCG.txt'
    'https://algs4.cs.princeton.edu/41graph/routes.txt'
    'https://algs4.cs.princeton.edu/41graph/moviesG.txt'
    'https://algs4.cs.princeton.edu/42digraph/tinyDG.txt'
    'https://algs4.cs.princeton.edu/42digraph/mediumDG.txt'
    'https://algs4.cs.princeton.edu/42digraph/largeDG.txt'
    'https://algs4.cs.princeton.edu/42digraph/tinyDAG.txt'
    'https://algs4.cs.princeton.edu/42digraph/jobs.txt'
    'https://algs4.cs.princeton.edu/43mst/tinyEWG.txt'
    'https://algs4.cs.princeton.edu/43mst/mediumEWG.txt'
    'https://algs4.cs.princeton.edu/43mst/largeEWG.txt'
    'https://algs4.cs.princeton.edu/44sp/tinyEWD.txt'
    'https://algs4.cs.princeton.edu/44sp/mediumEWD.txt'
    'https://algs4.cs.princeton.edu/44sp/largeEWD.txt'
    'https://algs4.cs.princeton.edu/44sp/tinyEWDAG.txt'
    'https://algs4.cs.princeton.edu/44sp/jobsPC.txt'
    'https://algs4.cs.princeton.edu/44sp/tinyEWDn.txt'
    'https://algs4.cs.princeton.edu/44sp/tinyEWDnc.txt'
    'https://algs4.cs.princeton.edu/44sp/rates.txt'
    'https://algs4.cs.princeton.edu/50strings/abra.txt'
    'https://algs4.cs.princeton.edu/50strings/pi.txt'
    'https://algs4.cs.princeton.edu/51radix/shells.txt'
    'https://algs4.cs.princeton.edu/52trie/shellsST.txt'
    'https://algs4.cs.princeton.edu/54regexp/tinyL.txt'
    'https://algs4.cs.princeton.edu/55compression/genomeTiny.txt'
    'https://algs4.cs.princeton.edu/55compression/tinytinyTale.txt'
    'https://algs4.cs.princeton.edu/55compression/medTale.txt'
    'https://algs4.cs.princeton.edu/55compression/abraLZW.txt'
    'https://algs4.cs.princeton.edu/55compression/ababLZW.txt'
    'https://algs4.cs.princeton.edu/61event/diffusion.txt'
    'https://algs4.cs.princeton.edu/61event/diffusion2.txt'
    'https://algs4.cs.princeton.edu/61event/diffusion3.txt'
    'https://algs4.cs.princeton.edu/61event/brownian.txt'
    'https://algs4.cs.princeton.edu/61event/brownian2.txt'
    'https://algs4.cs.princeton.edu/61event/billiards5.txt'
    'https://algs4.cs.princeton.edu/61event/pendulum.txt'
    'https://algs4.cs.princeton.edu/63suffix/mobydick.txt'
    'https://algs4.cs.princeton.edu/99hull/rs1423.txt'
    'https://algs4.cs.princeton.edu/99hull/kw1260.txt'
    'https://introcs.cs.princeton.edu/java/22library/tinyDouble1D.txt'
    'https://introcs.cs.princeton.edu/java/22library/tinyDouble2D.txt'
    'https://introcs.cs.princeton.edu/java/22library/tinyBoolean2D.txt'

    'https://algs4.cs.princeton.edu/35applications/DJIA.csv'
    'https://algs4.cs.princeton.edu/35applications/UPC.csv'
    'https://algs4.cs.princeton.edu/35applications/amino.csv'
    'https://algs4.cs.princeton.edu/35applications/elements.csv'
    'https://algs4.cs.princeton.edu/35applications/ip.csv'
    'https://algs4.cs.princeton.edu/35applications/morse.csv'
    'https://algs4.cs.princeton.edu/35applications/aminoI.csv'

    'https://algs4.cs.princeton.edu/55compression/4runs.bin'
    'https://algs4.cs.princeton.edu/55compression/q32x48.bin'
    'https://algs4.cs.princeton.edu/55compression/q64x96.bin'
)

# Make res directory if it doesn't exist
[ ! -d "./res" ] && mkdir res

# Download data files from Princeton website
for d in ${data_files[@]}; do
    wget -b -a log.txt -P ./res -nv -nc $d 
done